# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5d9dfbbcdab10e3e27f42e7474f26b2c21049076433b20eb2c6cc7307bcbb7725b3370bfa18f820e0a77f75f3135a9c96a3450cd89e102ec66a8c3e2240054

test:
  secret_key_base: 6a65f5c6ca339cf7e8084f41c2e76f1318837ff3c6a75acc6e5e0462ce4a0568bb57f83357741f5ee01a4695aef3bf1ca3aafac2180073be5ade00e89844aaf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
